### ISSUE TITLE
Make the homology migration re-entrant

### ISSUE THREAD

**Issue by mgrbyte** [WormBase/db-migration#39]
Attempt to remove any pre-existing homol databases before running homol import.
 1. delete any existing homol-helper db
 2. delete any existing homol db
 3. If 1 or 2 was true, the run `bin/datomic gc-deleted-dbs $transactor_host_url"

When the user runs the homology pipeline, if for any reason the step is aborted and re-run

**Comment by mluypaert** [comment]
Point 1 and 2 have been implemented through a [codechange in pseudoace](https://github.com/WormBase/pseudoace/commit/c2820d361401639b5887fdfc0daf8f3f9453bbf9).

Implementing 3 would be tricky, as there's not equivalent programmatic API endpoint.

Comment from Matt:
>For completeness, if implementing 3 was desired/needed, one would have to split out the deletion of the databases to another command, such that the commands to perform the homology migration change to:
>1. `delete-homol-dbs` (run d/delete-database for both the 'homol' and 'homol-helper' dbs
>2. run `bin/datomic gc-deleted-dbs`
>3. run `homol-import`
>
>Currently 1. and 3. are  rolled together (in 3)

Storage garbage-collection through `gc-deleted-dbs` is more important when using a storage on a long-term.
The storage used by the migration is blown away every release, so not worth the effort at this moment, hence this issue can be closed.
