### ISSUE TITLE
Fix deployment task order

### ISSUE THREAD

**Issue by mluypaert** [WormBase/db-migration#42]
Current deployment code produces a Github release (through a `zest.releaser` hook calling `github.publish_release`) before pushing any local commits or tags to Github. As a consequence, any unpushed local commits made before starting the release process (with `make release`) are not tagged as being part of the release, neither do the preparational commits made during the process. Although the asset (python wheel) creation is done correctly based on the local content, this mismatch between git tag and asset content can cause confusion, and needs fixing.

**Comment by MagdalenaZZ** [comment]
Seems you've got this in hand @mluypaert , give us a shout if you need anything.
